apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: new
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: snaveenkpn/test:9
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: new
spec:
  selector:
    app: node-app  # Change this line to match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 2500
      targetPort: 3000
  type: NodePort
